name: 'OpenSCAD Render'
description: ''
inputs:
  scad-file:
    description: 'relative path to the openscad file'
    required: true
    default: ''
  tag:
    description: 'value to use to tag compiled and rendered files'
    required: false
    default: 'compiled'
  openscad-version:
    description: 'openscad version to use to render files, based on dockerhub tags for openscad image'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
  - name: build container
    run: docker build --build-arg "SCAD_VERSION=$SCAD_VERSION" -t openscad "$GITHUB_ACTION_PATH"
    shell: bash
    env:
      SCAD_VERSION: ${{ inputs.openscad-version }}

  - name: run openscad build & render
    run: docker run -v "./:/github/workspace" -w "/github/workspace" openscad "$SCAD_FILE" "$TAG"
    shell: bash
    env:
      SCAD_FILE: ${{ inputs.scad-file }}
      TAG: ${{ inputs.tag }}