name: 'OpenSCAD Render'
description: ''
inputs:
  scad-file:
    description: 'relative path to the openscad file'
    required: true
    default: ''
  tag:
    description: ''
    required: false
    default: 'compiled'

runs:
  using: "composite"
  steps:
  - name: Set Variables
    id: set_variables
    run: |
      BASE_FILENAME="${SCAD_FILE%.*}"
      VERSION="${TAG:-$(date +"%Y%m%d-%H")}"
      VERSIONED_BASE_FILENAME="$BASE_FILENAME-$VERSION"
      
      echo "base_filename=$BASE_FILENAME" >> $GITHUB_OUTPUT
      echo "version=$VERSION" >> $GITHUB_OUTPUT
      echo "versioned_base_filename=$VERSIONED_BASE_FILENAME" >> $GITHUB_OUTPUT
    shell: bash
    env:
      SCAD_FILE: ${{ inputs.scad-file }}
      TAG: ${{ inputs.tag }}
  - name: Compile
    id: compile
    run: |
      ./compile.sh "$SCAD_FILE" "$VERSION"

      basefilename=$(basename $SCAD_FILE)
      echo "scadfile=$basefilename-$VERSION.scad" >> $GITHUB_OUTPUT
    shell: bash
    env:
      SCAD_FILE: ${{ inputs.scad-file }}
      VERSION: ${{ inputs.tag }}
  - name: Render
    id: render
    run: |
      ./render.sh "$COMPILED_SCAD_FILE" "$SCAD_FILE" "$VERSION"
    shell: bash
    env:
      COMPILED_SCAD_FILE: ${{ steps.compile.outputs.scadfile }}
      SCAD_FILE: ${{ inputs.scad-file }}
      VERSION: ${{ inputs.tag }}
  - name: Move Artifacts
    run: |
      mkdir ./output
      mv "$COMPILED_SCAD_FILE" ./output

      name_without_extension="${filename%.*}"
      mv "$name_without_extension*.stl" ./output
    shell: bash
    env:
      COMPILED_SCAD_FILE: ${{ steps.compile.outputs.scadfile }}